m1ct_d2_node:
  ros__parameters:
    port: /dev/sc_mini        # udev symlink para CH340 (VID=1a86 PID=7523)
    frame_id: base_laser      # coincide con el TF base_link→base_laser del bringup
    ignore_array: ""
    baudrate: 230400
    samp_rate: 9
    resolution_fixed: true
    singleChannel: false
    auto_reconnect: true
    reversion: true           # invierte ángulos: D6 usa left-hand (horario) → ROS right-hand
    isToFLidar: false
    angle_max: 180.0
    angle_min: -180.0
    max_range: 12.0           # COIN-D6: máximo 12m
    min_range: 0.05
    frequency: 10.0
    version: 4
